enabled: true
exclude:
  - "unzipper/modules/ext_script/ext_helper.py"
  - "unzipper/modules/ext_script/up_helper.py"
auto: false
pull_requests: true
commit_template: |
  Restyled by ${restyler.name}
statuses:
  differences: false
  no_differences: true
  error: true
labels:
  - style
restylers:
  - name: autopep8
  - name: isort
  - name: black
  - name: yapf
