name: Update Authors

on:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wow-actions/update-authors@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          sort: "commits"
          bots: true
          commit: "chore(authors) [skip ci]"
